sudo: false
language: c

matrix:
  include:
   - os: linux
   - os: osx 
     osx_image: Xcode 8.2

script:
  - (cd ./app/convbin/gcc/ && make clean all)

addons:
  artifacts:
    debug: true 
    paths:
      - ./app/convbin/gcc/convbin
    working_dir: $TRAVIS_BUILD_DIR
    target_paths: $TRAVIS_BUILD_NUMBER$TRAVIS_OS_NAME
    bucket: rtklib-ci-builds
    s3_region: us-west-2
