os: Visual Studio 2015

environment:
  matrix:
  - Compiler: mingw
  - Compiler: vs14

#cache:
#  - C:\mingw64

install:
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
  - set CC=gcc
  - set INCLUDE=%cd%\src;..\..\..\src;%INCLUDE%
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/mnaoumov/Invoke-NativeApplication/master/exec.ps1" -OutFile ".\exec1.ps1"

build_script:
  - ps: |
      if ($env:Compiler -eq "mingw") {
        cd ($env:APPVEYOR_BUILD_FOLDER + "\app\convbin\gcc")
        make clean all
      }
      if ($env:Compiler -eq "mingw") {
        cd ($env:APPVEYOR_BUILD_FOLDER + "\app\str2str\gcc")
        make clean all
      }
      if ($env:Compiler -eq "vs14") {
        cd ($env:APPVEYOR_BUILD_FOLDER + "\app\convbin\vs14")
        msbuild convbin-swiftnav.sln /p:Configuration=Release
        msbuild convbin-swiftnav.sln /p:Configuration=Debug
      }

artifacts:
  - path: app\convbin\gcc\sbp2rinex*
    name: sbp2rinex_mingw

  - path: app\str2str\gcc\str2str*
    name: sbp2str_mingw

  - path: app\convbin\vs14\Debug\sbp2rinex.exe
    name: sbp2rinex_vs_debug
  
  - path: app\convbin\vs14\Release\sbp2rinex.exe
    name: sbp2rinex_vs_release

test_script:
  - ps: |
      if ($env:Compiler -eq "mingw") {
        . ($env:APPVEYOR_BUILD_FOLDER + "\exec1.ps1")
        cd ($env:APPVEYOR_BUILD_FOLDER + "\app\convbin\gcc")
        exec {& make test}
      }
  - ps: |
      if ($env:Compiler -eq "vs14") {
        . ($env:APPVEYOR_BUILD_FOLDER + "\exec1.ps1")
        cd ($env:APPVEYOR_BUILD_FOLDER + "\app\convbin\vs14\Release")
        echo ""
        echo "******Test1 sbp2rinex on sbp binary*****"
        echo ""
        exec {& .\sbp2rinex ($env:APPVEYOR_BUILD_FOLDER + "\test\data\rcvraw\2017-05-12-v1.1.26.sbp") -o 2017-05-12-v1.1.26.sbp.obs -n 2017-05-12-v1.1.26.sbp.nav } 
        echo ""
        echo "******Test2 sbp2rinex on sbp json*****"
        echo ""
        exec {& .\sbp2rinex ($env:APPVEYOR_BUILD_FOLDER + "\test\data\rcvraw\2017-05-12-v1.1.26.sbp.json") -o 2017-05-12-v1.1.26.sbp.json.obs -n 2017-05-12-v1.1.26.sbp.json.nav } 
        #& .\sbp2rinex ($env:APPVEYOR_BUILD_FOLDER + "\test\data\rcvraw\2017-05-12-v1.1.26-spaces.sbp.json") -o 2017-05-12-v1.1.26-nospaces.sbp.json.obs -n 2017-05-12-v1.1.26-nospaces.sbp.json.nav | out-null
        echo ""
        echo "******Test3 compare outputs from json and binary*****"
        echo ""
        diff (gc 2017-05-12-v1.1.26.sbp.obs | select -Skip 5 ) (gc 2017-05-12-v1.1.26.sbp.json.obs | select -Skip 5 ) 
        echo ""
        echo "******Test4 sbp2rinex on sbp json without spaces*****"
        echo ""
        exec {& .\sbp2rinex ($env:APPVEYOR_BUILD_FOLDER + "\test\data\rcvraw\2017-05-12-v1.1.26-nospaces.sbp.json") -o 2017-05-12-v1.1.26-nospaces.sbp.json.obs -n 2017-05-12-v1.1.26-nospaces.sbp.json.nav } 
        echo ""
        echo "******Test5 compare outputs from json without spaces and binary*****"
        echo ""
        diff (gc 2017-05-12-v1.1.26.sbp.obs | select -Skip 5 ) (gc 2017-05-12-v1.1.26-nospaces.sbp.json.obs | select -Skip 5 ) 
      }
